-- BÁO CÁO TIN NHẮN CÔNG KHAI
-- Chạy sau 11_friendships_ids_roles.sql.

create table if not exists public.public_message_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null
    references public.profiles(id)
    on delete cascade,
  reported_user_id uuid not null
    references public.profiles(id)
    on delete cascade,
  message_id bigint
    references public.messages(id)
    on delete set null,
  category text not null
    check (
      category in (
        'profanity',
        'sexual_content',
        'illegal_content',
        'spam_scam',
        'other'
      )
    ),
  details text,
  message_content text not null default '',
  attachment_url text,
  channel text not null default 'chung',
  status text not null default 'pending'
    check (
      status in (
        'pending',
        'reviewing',
        'resolved',
        'dismissed'
      )
    ),
  handled_by uuid
    references public.profiles(id)
    on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint public_message_reports_not_self
    check (reporter_id <> reported_user_id),
  constraint public_message_reports_details_length
    check (
      details is null
      or char_length(details) <= 500
    )
);

create index if not exists
  public_message_reports_status_created_idx
on public.public_message_reports (
  status,
  created_at desc
);

create index if not exists
  public_message_reports_reported_user_idx
on public.public_message_reports (
  reported_user_id,
  created_at desc
);

create unique index if not exists
  public_message_reports_active_unique_idx
on public.public_message_reports (
  reporter_id,
  message_id
)
where
  message_id is not null
  and status in ('pending', 'reviewing');

alter table public.public_message_reports
enable row level security;

drop policy if exists
  "Users can read own reports"
on public.public_message_reports;

create policy
  "Users can read own reports"
on public.public_message_reports
for select
to authenticated
using (
  reporter_id = auth.uid()
  or public.is_staff()
);

drop policy if exists
  "Staff can update reports"
on public.public_message_reports;

create policy
  "Staff can update reports"
on public.public_message_reports
for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists
  "Staff can delete reports"
on public.public_message_reports;

create policy
  "Staff can delete reports"
on public.public_message_reports
for delete
to authenticated
using (public.is_staff());

grant select, update, delete
on public.public_message_reports
to authenticated;

create or replace function public.report_public_message(
  p_message_id bigint,
  p_category text,
  p_details text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  target_message public.messages;
  created_report_id bigint;
  clean_details text :=
    nullif(btrim(coalesce(p_details, '')), '');
begin
  if current_user_id is null then
    raise exception 'Bạn chưa đăng nhập.'
      using errcode = '42501';
  end if;

  if p_category not in (
    'profanity',
    'sexual_content',
    'illegal_content',
    'spam_scam',
    'other'
  ) then
    raise exception 'Lý do báo cáo không hợp lệ.'
      using errcode = '22023';
  end if;

  if clean_details is not null
     and char_length(clean_details) > 500 then
    raise exception 'Mô tả báo cáo tối đa 500 ký tự.'
      using errcode = '22001';
  end if;

  select *
  into target_message
  from public.messages
  where id = p_message_id;

  if not found then
    raise exception 'Tin nhắn không còn tồn tại.'
      using errcode = 'P0002';
  end if;

  if target_message.user_id = current_user_id then
    raise exception 'Bạn không thể báo cáo tin nhắn của chính mình.'
      using errcode = '22023';
  end if;

  insert into public.public_message_reports (
    reporter_id,
    reported_user_id,
    message_id,
    category,
    details,
    message_content,
    attachment_url,
    channel
  )
  values (
    current_user_id,
    target_message.user_id,
    target_message.id,
    p_category,
    clean_details,
    coalesce(target_message.content, ''),
    target_message.attachment_url,
    target_message.channel
  )
  returning id
  into created_report_id;

  return created_report_id;
exception
  when unique_violation then
    raise exception 'Bạn đã báo cáo tin nhắn này và báo cáo đang chờ xử lý.'
      using errcode = 'P0001';
end;
$$;

create or replace function public.staff_list_message_reports()
returns table(
  report_id bigint,
  message_id bigint,
  reporter_id uuid,
  reporter_username text,
  reporter_public_id bigint,
  reported_user_id uuid,
  reported_username text,
  reported_public_id bigint,
  reported_role text,
  category text,
  details text,
  message_content text,
  attachment_url text,
  channel text,
  status text,
  created_at timestamptz,
  handled_by uuid,
  handled_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_staff() then
    raise exception 'Bạn không có quyền quản trị.'
      using errcode = '42501';
  end if;

  return query
  select
    r.id,
    r.message_id,
    r.reporter_id,
    reporter.username,
    reporter.public_id,
    r.reported_user_id,
    reported.username,
    reported.public_id,
    coalesce(reported_role.role, 'member'),
    r.category,
    r.details,
    r.message_content,
    r.attachment_url,
    r.channel,
    r.status,
    r.created_at,
    r.handled_by,
    r.handled_at
  from public.public_message_reports r
  join public.profiles reporter
    on reporter.id = r.reporter_id
  join public.profiles reported
    on reported.id = r.reported_user_id
  left join public.user_roles reported_role
    on reported_role.user_id = r.reported_user_id
  order by
    case r.status
      when 'pending' then 0
      when 'reviewing' then 1
      when 'resolved' then 2
      else 3
    end,
    r.created_at desc;
end;
$$;

create or replace function public.staff_update_message_report(
  p_report_id bigint,
  p_status text
)
returns public.public_message_reports
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_report public.public_message_reports;
begin
  if not public.is_staff() then
    raise exception 'Bạn không có quyền quản trị.'
      using errcode = '42501';
  end if;

  if p_status not in (
    'pending',
    'reviewing',
    'resolved',
    'dismissed'
  ) then
    raise exception 'Trạng thái báo cáo không hợp lệ.'
      using errcode = '22023';
  end if;

  update public.public_message_reports
  set
    status = p_status,
    handled_by = case
      when p_status in ('resolved', 'dismissed')
      then auth.uid()
      else null
    end,
    handled_at = case
      when p_status in ('resolved', 'dismissed')
      then now()
      else null
    end,
    updated_at = now()
  where id = p_report_id
  returning *
  into updated_report;

  if not found then
    raise exception 'Không tìm thấy báo cáo.'
      using errcode = 'P0002';
  end if;

  return updated_report;
end;
$$;

revoke all
on function public.report_public_message(
  bigint,
  text,
  text
)
from public;

revoke all
on function public.staff_list_message_reports()
from public;

revoke all
on function public.staff_update_message_report(
  bigint,
  text
)
from public;

grant execute
on function public.report_public_message(
  bigint,
  text,
  text
)
to authenticated;

grant execute
on function public.staff_list_message_reports()
to authenticated;

grant execute
on function public.staff_update_message_report(
  bigint,
  text
)
to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'public_message_reports'
  ) then
    alter publication supabase_realtime
      add table public.public_message_reports;
  end if;
end
$$;
