-- WEB PUSH: THÔNG BÁO TIN NHẮN, LỜI MỜI VÀ CUỘC GỌI
-- Chạy toàn bộ file trong Supabase SQL Editor.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null
    references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  expiration_time bigint,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists
  push_subscriptions_endpoint_uidx
on public.push_subscriptions(endpoint);

create index if not exists
  push_subscriptions_user_idx
on public.push_subscriptions(user_id, enabled);

alter table public.push_subscriptions
  enable row level security;

grant select, insert, update, delete
on public.push_subscriptions
to authenticated;

drop policy if exists
  "Users read own push subscriptions"
on public.push_subscriptions;

create policy
  "Users read own push subscriptions"
on public.push_subscriptions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists
  "Users insert own push subscriptions"
on public.push_subscriptions;

create policy
  "Users insert own push subscriptions"
on public.push_subscriptions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists
  "Users update own push subscriptions"
on public.push_subscriptions;

create policy
  "Users update own push subscriptions"
on public.push_subscriptions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists
  "Users delete own push subscriptions"
on public.push_subscriptions;

create policy
  "Users delete own push subscriptions"
on public.push_subscriptions
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function
  public.touch_push_subscription_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists
  touch_push_subscription_updated_at_trigger
on public.push_subscriptions;

create trigger
  touch_push_subscription_updated_at_trigger
before update on public.push_subscriptions
for each row
execute function
  public.touch_push_subscription_updated_at();
