-- TRẢ LỜI VÀ THẢ CẢM XÚC TRONG TIN NHẮN RIÊNG
-- Chạy toàn bộ file này trong Supabase SQL Editor.

alter table public.direct_messages
  add column if not exists reply_to_id bigint
    references public.direct_messages(id)
    on delete set null;

create index if not exists
  direct_messages_reply_to_id_idx
on public.direct_messages(reply_to_id);

create table if not exists
  public.direct_message_reactions (
    id bigint generated by default as identity primary key,
    message_id bigint not null
      references public.direct_messages(id)
      on delete cascade,
    user_id uuid not null
      references auth.users(id)
      on delete cascade,
    emoji text not null
      check (
        char_length(emoji) between 1 and 16
      ),
    created_at timestamptz not null default now(),
    unique(message_id, user_id, emoji)
  );

create index if not exists
  direct_message_reactions_message_idx
on public.direct_message_reactions(message_id);

alter table public.direct_message_reactions
  enable row level security;

grant select, insert, delete
on public.direct_message_reactions
to authenticated;

drop policy if exists
  "Participants read direct reactions"
on public.direct_message_reactions;

create policy
  "Participants read direct reactions"
on public.direct_message_reactions
for select
to authenticated
using (
  exists (
    select 1
    from public.direct_messages message
    where message.id =
      direct_message_reactions.message_id
      and auth.uid() in (
        message.sender_id,
        message.receiver_id
      )
  )
);

drop policy if exists
  "Participants add direct reactions"
on public.direct_message_reactions;

create policy
  "Participants add direct reactions"
on public.direct_message_reactions
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.direct_messages message
    where message.id =
      direct_message_reactions.message_id
      and auth.uid() in (
        message.sender_id,
        message.receiver_id
      )
  )
);

drop policy if exists
  "Users remove own direct reactions"
on public.direct_message_reactions;

create policy
  "Users remove own direct reactions"
on public.direct_message_reactions
for delete
to authenticated
using (
  auth.uid() = user_id
);

alter table public.direct_message_reactions
  replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename =
        'direct_message_reactions'
  ) then
    alter publication supabase_realtime
      add table
        public.direct_message_reactions;
  end if;
end
$$;
