-- ============================================================
-- TALK CÙNG LÂM DZ - Ô CHỜ, CHỦ PHÒNG VÀ MỜI BẠN CHƠI GAME
-- Chạy một lần sau 23_game_channels.sql.
-- ============================================================

begin;

-- 1. Mỗi người chơi có một vị trí cố định trong phòng chờ.
alter table public.game_channel_players
  add column if not exists seat_index integer;

with ranked as (
  select
    channel_id,
    user_id,
    row_number() over (
      partition by channel_id
      order by joined_at asc, user_id asc
    ) - 1 as next_seat
  from public.game_channel_players
)
update public.game_channel_players p
set seat_index = ranked.next_seat
from ranked
where ranked.channel_id = p.channel_id
  and ranked.user_id = p.user_id
  and p.seat_index is null;

alter table public.game_channel_players
  alter column seat_index set not null;

alter table public.game_channel_players
  drop constraint if exists game_channel_players_seat_range;

alter table public.game_channel_players
  add constraint game_channel_players_seat_range
  check (seat_index between 0 and 31);

create unique index if not exists
game_channel_players_channel_seat_uidx
on public.game_channel_players(channel_id, seat_index);

-- 2. Lời mời bạn bè gắn với đúng ô chờ.
create table if not exists public.game_channel_invites (
  id bigint generated by default as identity primary key,
  channel_id uuid not null
    references public.channels(id) on delete cascade,
  seat_index integer not null check (seat_index between 0 and 31),
  inviter_id uuid not null
    references auth.users(id) on delete cascade,
  invitee_id uuid not null
    references auth.users(id) on delete cascade,
  status text not null default 'pending'
    check (status in (
      'pending', 'accepted', 'declined', 'cancelled', 'expired'
    )),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  responded_at timestamptz,
  constraint game_channel_invites_not_self
    check (inviter_id <> invitee_id)
);

create unique index if not exists
game_channel_invites_pending_seat_uidx
on public.game_channel_invites(channel_id, seat_index)
where status = 'pending';

create unique index if not exists
game_channel_invites_pending_user_uidx
on public.game_channel_invites(channel_id, invitee_id)
where status = 'pending';

create index if not exists
game_channel_invites_invitee_idx
on public.game_channel_invites(invitee_id, status, created_at desc);

alter table public.game_channel_invites enable row level security;
grant select on public.game_channel_invites to authenticated;

drop policy if exists "Visible game channel invites"
on public.game_channel_invites;
create policy "Visible game channel invites"
on public.game_channel_invites for select to authenticated
using (public.channel_can_view(channel_id, auth.uid()));

alter table public.game_channel_invites replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'game_channel_invites'
  ) then
    alter publication supabase_realtime
      add table public.game_channel_invites;
  end if;
end
$$;

-- 3. Dọn người mất kết nối, lời mời hết hạn và giữ ô số 1
-- luôn là ô của chủ phòng.
create or replace function public.normalize_game_channel_lobby(
  p_channel_id uuid
)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  next_host_id uuid;
begin
  update public.game_channel_invites
  set
    status = 'expired',
    responded_at = now()
  where channel_id = p_channel_id
    and status = 'pending'
    and expires_at <= now();

  delete from public.game_channel_players
  where channel_id = p_channel_id
    and last_seen_at <= now() - interval '2 minutes';

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
  ) and not exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and seat_index = 0
  ) then
    select user_id
    into next_host_id
    from public.game_channel_players
    where channel_id = p_channel_id
    order by seat_index asc, joined_at asc
    limit 1;

    update public.game_channel_players
    set seat_index = 0
    where channel_id = p_channel_id
      and user_id = next_host_id;
  end if;
end;
$$;

-- 4. Trả danh sách người theo đúng vị trí ô chờ.
drop function if exists public.get_game_channel_players(uuid);

create function public.get_game_channel_players(
  p_channel_id uuid
)
returns table(
  id uuid,
  username text,
  avatar_url text,
  public_id bigint,
  role text,
  is_ready boolean,
  joined_at timestamptz,
  seat_index integer
)
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.channel_can_view(p_channel_id, auth.uid()) then
    raise exception 'Bạn không có quyền xem kênh game này.'
      using errcode = '42501';
  end if;

  return query
  select
    p.user_id,
    coalesce(pr.username, 'Người chơi'),
    pr.avatar_url,
    pr.public_id,
    coalesce(ur.role, 'member'),
    p.is_ready,
    p.joined_at,
    p.seat_index
  from public.game_channel_players p
  join public.profiles pr on pr.id = p.user_id
  left join public.user_roles ur on ur.user_id = p.user_id
  where p.channel_id = p_channel_id
    and p.last_seen_at > now() - interval '2 minutes'
  order by p.seat_index asc;
end;
$$;

create or replace function public.get_game_channel_invites(
  p_channel_id uuid
)
returns table(
  invite_id bigint,
  seat_index integer,
  invitee_id uuid,
  username text,
  avatar_url text,
  public_id bigint,
  role text,
  inviter_username text,
  created_at timestamptz
)
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.channel_can_view(p_channel_id, auth.uid()) then
    raise exception 'Bạn không có quyền xem lời mời của kênh game này.'
      using errcode = '42501';
  end if;

  return query
  select
    i.id,
    i.seat_index,
    i.invitee_id,
    coalesce(invitee.username, 'Người chơi'),
    invitee.avatar_url,
    invitee.public_id,
    coalesce(ur.role, 'member'),
    coalesce(inviter.username, 'Một người bạn'),
    i.created_at
  from public.game_channel_invites i
  join public.profiles invitee on invitee.id = i.invitee_id
  join public.profiles inviter on inviter.id = i.inviter_id
  left join public.user_roles ur on ur.user_id = i.invitee_id
  where i.channel_id = p_channel_id
    and i.status = 'pending'
    and i.expires_at > now()
  order by i.seat_index asc;
end;
$$;

create or replace function public.get_invitable_game_friends(
  p_channel_id uuid
)
returns table(
  id uuid,
  username text,
  avatar_url text,
  public_id bigint,
  role text
)
language plpgsql stable security definer set search_path = ''
as $$
declare
  target_server_id uuid;
begin
  if not public.channel_can_view(p_channel_id, auth.uid()) then
    raise exception 'Bạn không có quyền mời người vào kênh game này.'
      using errcode = '42501';
  end if;

  select server_id into target_server_id
  from public.channels
  where id = p_channel_id;

  return query
  select
    pr.id,
    pr.username,
    pr.avatar_url,
    pr.public_id,
    coalesce(ur.role, 'member')
  from public.friendships f
  join public.profiles pr on pr.id = f.friend_id
  join public.server_members sm
    on sm.server_id = target_server_id
    and sm.user_id = pr.id
  left join public.user_roles ur on ur.user_id = pr.id
  where f.user_id = auth.uid()
    and not exists(
      select 1
      from public.game_channel_players gp
      where gp.channel_id = p_channel_id
        and gp.user_id = pr.id
    )
    and not exists(
      select 1
      from public.game_channel_invites gi
      where gi.channel_id = p_channel_id
        and gi.invitee_id = pr.id
        and gi.status = 'pending'
        and gi.expires_at > now()
    )
  order by pr.username asc;
end;
$$;

-- 5. Tham gia đúng ô. Người đầu tiên luôn được đưa vào ô số 1.
-- Xóa cả chữ ký cũ một tham số và chữ ký mới hai tham số.
-- Nhờ vậy file có thể chạy lại kể cả khi một lần cài trước đã
-- tạo join_game_channel(uuid, integer).
drop function if exists public.join_game_channel(uuid);
drop function if exists public.join_game_channel(uuid, integer);

create function public.join_game_channel(
  p_channel_id uuid,
  p_seat_index integer default null
)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  maximum_players integer;
  target_seat integer;
  current_count integer;
begin
  if not public.channel_can_view(p_channel_id, auth.uid()) then
    raise exception 'Bạn không có quyền vào kênh game này.'
      using errcode = '42501';
  end if;

  perform public.normalize_game_channel_lobby(p_channel_id);

  select g.max_players
  into maximum_players
  from public.game_channel_states s
  join public.game_catalog g on g.game_key = s.game_key
  join public.channels c on c.id = s.channel_id
  where s.channel_id = p_channel_id
    and c.channel_type = 'game'
    and g.is_active;

  if maximum_players is null then
    raise exception 'Kênh chưa chọn game.';
  end if;

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and user_id = auth.uid()
  ) then
    update public.game_channel_players
    set last_seen_at = now()
    where channel_id = p_channel_id
      and user_id = auth.uid();
    return true;
  end if;

  select count(*) into current_count
  from public.game_channel_players
  where channel_id = p_channel_id;

  if current_count >= maximum_players then
    raise exception 'Phòng game đã đủ người.';
  end if;

  if current_count = 0 then
    target_seat := 0;
  elsif p_seat_index is not null then
    target_seat := p_seat_index;
  else
    select seat_number
    into target_seat
    from generate_series(0, maximum_players - 1) seat_number
    where not exists(
      select 1
      from public.game_channel_players p
      where p.channel_id = p_channel_id
        and p.seat_index = seat_number
    )
      and not exists(
        select 1
        from public.game_channel_invites i
        where i.channel_id = p_channel_id
          and i.seat_index = seat_number
          and i.status = 'pending'
          and i.expires_at > now()
      )
    order by seat_number
    limit 1;
  end if;

  if target_seat is null
    or target_seat < 0
    or target_seat >= maximum_players then
    raise exception 'Vị trí chờ không hợp lệ.';
  end if;

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and seat_index = target_seat
  ) or exists(
    select 1
    from public.game_channel_invites
    where channel_id = p_channel_id
      and seat_index = target_seat
      and status = 'pending'
      and expires_at > now()
  ) then
    raise exception 'Ô chờ này đã có người hoặc đã được giữ chỗ.';
  end if;

  insert into public.game_channel_players(
    channel_id, user_id, seat_index,
    is_ready, joined_at, last_seen_at
  )
  values(
    p_channel_id, auth.uid(), target_seat,
    false, now(), now()
  );

  update public.game_channel_invites
  set
    status = 'cancelled',
    responded_at = now()
  where channel_id = p_channel_id
    and invitee_id = auth.uid()
    and status = 'pending';

  return true;
end;
$$;

create or replace function public.move_game_channel_seat(
  p_channel_id uuid,
  p_seat_index integer
)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  maximum_players integer;
  current_seat integer;
begin
  perform public.normalize_game_channel_lobby(p_channel_id);

  select g.max_players
  into maximum_players
  from public.game_channel_states s
  join public.game_catalog g on g.game_key = s.game_key
  where s.channel_id = p_channel_id;

  select seat_index into current_seat
  from public.game_channel_players
  where channel_id = p_channel_id
    and user_id = auth.uid()
  for update;

  if current_seat is null then
    raise exception 'Bạn chưa tham gia phòng game.';
  end if;

  if current_seat = 0 then
    raise exception 'Chủ phòng phải ở ô số 1. Hãy rời phòng để chuyển chủ.';
  end if;

  if p_seat_index <= 0 or p_seat_index >= maximum_players then
    raise exception 'Vị trí chờ không hợp lệ.';
  end if;

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and seat_index = p_seat_index
  ) or exists(
    select 1
    from public.game_channel_invites
    where channel_id = p_channel_id
      and seat_index = p_seat_index
      and status = 'pending'
      and expires_at > now()
  ) then
    raise exception 'Ô chờ này đã có người hoặc đã được giữ chỗ.';
  end if;

  update public.game_channel_players
  set
    seat_index = p_seat_index,
    last_seen_at = now()
  where channel_id = p_channel_id
    and user_id = auth.uid();

  return true;
end;
$$;

-- 6. Mời một người bạn đang là thành viên của server vào ô chờ.
create or replace function public.invite_friend_to_game_channel(
  p_channel_id uuid,
  p_friend_id uuid,
  p_seat_index integer
)
returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  maximum_players integer;
  target_server_id uuid;
  target_seat integer := p_seat_index;
  new_invite_id bigint;
  current_count integer;
begin
  if not public.channel_can_view(p_channel_id, auth.uid()) then
    raise exception 'Bạn không có quyền mời người vào kênh game này.'
      using errcode = '42501';
  end if;

  perform public.normalize_game_channel_lobby(p_channel_id);

  select c.server_id, g.max_players
  into target_server_id, maximum_players
  from public.channels c
  join public.game_channel_states s on s.channel_id = c.id
  join public.game_catalog g on g.game_key = s.game_key
  where c.id = p_channel_id
    and c.channel_type = 'game';

  if maximum_players is null then
    raise exception 'Kênh chưa chọn game.';
  end if;

  if not exists(
    select 1
    from public.friendships
    where user_id = auth.uid()
      and friend_id = p_friend_id
  ) then
    raise exception 'Bạn chỉ có thể mời người trong danh sách bạn bè.';
  end if;

  if not exists(
    select 1
    from public.server_members
    where server_id = target_server_id
      and user_id = p_friend_id
  ) then
    raise exception 'Người bạn này chưa tham gia server.';
  end if;

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and user_id = p_friend_id
  ) then
    raise exception 'Người bạn này đã ở trong phòng chờ.';
  end if;

  select count(*) into current_count
  from public.game_channel_players
  where channel_id = p_channel_id;

  if current_count = 0 then target_seat := 0; end if;

  if target_seat < 0 or target_seat >= maximum_players then
    raise exception 'Vị trí chờ không hợp lệ.';
  end if;

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and seat_index = target_seat
  ) or exists(
    select 1
    from public.game_channel_invites
    where channel_id = p_channel_id
      and seat_index = target_seat
      and status = 'pending'
      and expires_at > now()
  ) then
    raise exception 'Ô chờ này đã có người hoặc đã được giữ chỗ.';
  end if;

  update public.game_channel_invites
  set
    status = 'cancelled',
    responded_at = now()
  where channel_id = p_channel_id
    and invitee_id = p_friend_id
    and status = 'pending';

  insert into public.game_channel_invites(
    channel_id, seat_index, inviter_id, invitee_id
  )
  values(
    p_channel_id, target_seat, auth.uid(), p_friend_id
  )
  returning id into new_invite_id;

  return new_invite_id;
end;
$$;

create or replace function public.respond_game_channel_invite(
  p_invite_id bigint,
  p_accept boolean
)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  target_invite public.game_channel_invites%rowtype;
  maximum_players integer;
  current_count integer;
  target_seat integer;
begin
  select * into target_invite
  from public.game_channel_invites
  where id = p_invite_id
    and invitee_id = auth.uid()
    and status = 'pending'
  for update;

  if target_invite.id is null then
    raise exception 'Lời mời không còn hiệu lực.';
  end if;

  if target_invite.expires_at <= now() then
    update public.game_channel_invites
    set status = 'expired', responded_at = now()
    where id = p_invite_id;
    raise exception 'Lời mời đã hết hạn.';
  end if;

  if not coalesce(p_accept, false) then
    update public.game_channel_invites
    set status = 'declined', responded_at = now()
    where id = p_invite_id;
    return true;
  end if;

  perform public.normalize_game_channel_lobby(
    target_invite.channel_id
  );

  select g.max_players
  into maximum_players
  from public.game_channel_states s
  join public.game_catalog g on g.game_key = s.game_key
  where s.channel_id = target_invite.channel_id;

  select count(*) into current_count
  from public.game_channel_players
  where channel_id = target_invite.channel_id;

  target_seat := case
    when current_count = 0 then 0
    else target_invite.seat_index
  end;

  if current_count >= maximum_players then
    raise exception 'Phòng game đã đủ người.';
  end if;

  if exists(
    select 1
    from public.game_channel_players
    where channel_id = target_invite.channel_id
      and seat_index = target_seat
  ) then
    raise exception 'Ô chờ được mời đã có người.';
  end if;

  insert into public.game_channel_players(
    channel_id, user_id, seat_index,
    is_ready, joined_at, last_seen_at
  )
  values(
    target_invite.channel_id, auth.uid(), target_seat,
    false, now(), now()
  )
  on conflict (channel_id, user_id) do update
  set
    seat_index = excluded.seat_index,
    last_seen_at = now();

  update public.game_channel_invites
  set
    status = case
      when id = p_invite_id then 'accepted'
      else 'cancelled'
    end,
    responded_at = now()
  where channel_id = target_invite.channel_id
    and status = 'pending'
    and (
      invitee_id = auth.uid()
      or seat_index = target_seat
    );

  return true;
end;
$$;

-- 7. Rời phòng, chuyển chủ và bắt đầu trò chơi.
create or replace function public.leave_game_channel(
  p_channel_id uuid
)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  leaving_seat integer;
  next_host_id uuid;
begin
  select seat_index into leaving_seat
  from public.game_channel_players
  where channel_id = p_channel_id
    and user_id = auth.uid();

  delete from public.game_channel_players
  where channel_id = p_channel_id
    and user_id = auth.uid();

  if leaving_seat = 0 then
    select user_id into next_host_id
    from public.game_channel_players
    where channel_id = p_channel_id
    order by seat_index asc, joined_at asc
    limit 1;

    if next_host_id is not null then
      update public.game_channel_players
      set seat_index = 0
      where channel_id = p_channel_id
        and user_id = next_host_id;
    end if;
  end if;

  update public.game_channel_invites
  set
    status = 'cancelled',
    responded_at = now()
  where channel_id = p_channel_id
    and inviter_id = auth.uid()
    and status = 'pending';

  return true;
end;
$$;

create or replace function public.start_game_channel(
  p_channel_id uuid
)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  player_count integer;
  not_ready_count integer;
begin
  perform public.normalize_game_channel_lobby(p_channel_id);

  if not exists(
    select 1
    from public.game_channel_players
    where channel_id = p_channel_id
      and user_id = auth.uid()
      and seat_index = 0
  ) then
    raise exception 'Chỉ chủ phòng ở ô số 1 mới được bắt đầu.';
  end if;

  select
    count(*),
    count(*) filter (where not is_ready)
  into player_count, not_ready_count
  from public.game_channel_players
  where channel_id = p_channel_id;

  if player_count < 2 then
    raise exception 'Cần ít nhất 2 người để bắt đầu.';
  end if;

  if not_ready_count > 0 then
    raise exception 'Tất cả người chơi phải sẵn sàng.';
  end if;

  update public.game_channel_states
  set
    status = 'playing',
    updated_by = auth.uid(),
    updated_at = now()
  where channel_id = p_channel_id;

  return true;
end;
$$;

-- Khi đổi game, xóa cả lời mời giữ chỗ của game cũ.
create or replace function public.reset_game_invites_on_game_change()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if old.game_key is distinct from new.game_key then
    update public.game_channel_invites
    set
      status = 'cancelled',
      responded_at = now()
    where channel_id = new.channel_id
      and status = 'pending';
  end if;
  return new;
end;
$$;

drop trigger if exists reset_game_invites_on_game_change_trigger
on public.game_channel_states;

create trigger reset_game_invites_on_game_change_trigger
after update of game_key on public.game_channel_states
for each row execute function public.reset_game_invites_on_game_change();

-- 8. Quyền thực thi API.
revoke all on function public.normalize_game_channel_lobby(uuid)
from public;
revoke all on function public.get_game_channel_players(uuid)
from public;
revoke all on function public.get_game_channel_invites(uuid)
from public;
revoke all on function public.get_invitable_game_friends(uuid)
from public;
revoke all on function public.join_game_channel(uuid,integer)
from public;
revoke all on function public.move_game_channel_seat(uuid,integer)
from public;
revoke all on function public.invite_friend_to_game_channel(uuid,uuid,integer)
from public;
revoke all on function public.respond_game_channel_invite(bigint,boolean)
from public;
revoke all on function public.leave_game_channel(uuid)
from public;
revoke all on function public.start_game_channel(uuid)
from public;

grant execute on function public.get_game_channel_players(uuid)
to authenticated;
grant execute on function public.get_game_channel_invites(uuid)
to authenticated;
grant execute on function public.get_invitable_game_friends(uuid)
to authenticated;
grant execute on function public.join_game_channel(uuid,integer)
to authenticated;
grant execute on function public.move_game_channel_seat(uuid,integer)
to authenticated;
grant execute on function public.invite_friend_to_game_channel(uuid,uuid,integer)
to authenticated;
grant execute on function public.respond_game_channel_invite(bigint,boolean)
to authenticated;
grant execute on function public.leave_game_channel(uuid)
to authenticated;
grant execute on function public.start_game_channel(uuid)
to authenticated;

notify pgrst, 'reload schema';

commit;
